#!/usr/bin/env node
// Generates level/city/src/voxel/materials.{hpp,cpp} from the reference's voxel/materials.js:
// the city's palette (ids in definition order, names, colours, flags) as C++ data.
//   node tools/procgen_ref/gen_materials.mjs
import { writeFileSync } from "node:fs";
import { REF } from "./lib/rec.mjs";

const { MATERIALS, MAX_MATERIALS } = await import(REF + "voxel/materials.js");
const out = new URL("../../level/city/src/voxel/", import.meta.url);
const num = (v) => (Number.isInteger(v) ? `${v}.0` : String(v));
const hpp = `// svx_city — the voxel material palette (voxel_city voxel/materials.js), generated from the
// reference by tools/procgen_ref/gen_materials.mjs: do not edit. Ids are uint16 in definition
// order (0 air); each carries a base colour and rendering flags.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace svx::city {

constexpr int kMaxMaterials = ${MAX_MATERIALS};
constexpr int kMaterialCount = ${MATERIALS.length};

// MAT.NAME
namespace MAT {
enum : uint16_t {
${MATERIALS.map((m) => `  ${m.name} = ${m.id},`).join("\n")}
};
}  // namespace MAT

struct MaterialInfo {
  uint16_t id;
  const char* name;
  std::array<uint8_t, 3> rgb;
  double noise;
  bool transparent;
  double opacity;
  double emissive;
  bool solid;
  bool climb;
  bool glow;
};

// MATERIALS[id] (id < kMaterialCount)
const MaterialInfo& material_info(int id);
// MAT[name], or -1 (undefined) when there is none
int material_id(std::string_view name);
// IS_TRANSPARENT, IS_SOLID, IS_CLIMB (0 beyond the palette)
bool is_transparent(int id);
bool is_solid(int id);
bool is_climb(int id);

}  // namespace svx::city
`;
const cpp = `// svx_city — voxel/materials.hpp's data, generated by tools/procgen_ref/gen_materials.mjs.
#include "voxel/materials.hpp"

#include <string_view>

namespace svx::city {

namespace {
const MaterialInfo kMaterials[kMaterialCount] = {
${MATERIALS.map((m) => `    {${m.id}, "${m.name}", {${m.rgb.join(", ")}}, ${num(m.noise)}, ${m.transparent}, ${num(m.opacity)}, ${num(m.emissive)}, ${m.solid}, ${m.climb}, ${m.glow}},`).join("\n")}
};
}  // namespace

const MaterialInfo& material_info(int id) { return kMaterials[id]; }

int material_id(std::string_view name) {
  for (const MaterialInfo& m : kMaterials)
    if (name == m.name) return m.id;
  return -1;
}

bool is_transparent(int id) { return id >= 0 && id < kMaterialCount && kMaterials[id].transparent; }
bool is_solid(int id) { return id >= 0 && id < kMaterialCount && kMaterials[id].solid; }
bool is_climb(int id) { return id >= 0 && id < kMaterialCount && kMaterials[id].climb; }

}  // namespace svx::city
`;
writeFileSync(new URL("materials.hpp", out), hpp);
writeFileSync(new URL("materials.cpp", out), cpp);
console.log(`${MATERIALS.length} materials`);
