# Writes OUT: the JSON files under DIR as a C++ table of {path, text} returned by
# NAMESPACE::FUNCTION() (declared in HEADER: `const std::vector<EmbeddedFile>& FUNCTION();`), so
# every build - WASM too - carries them. Run at build time (add_custom_command): a changed file
# rebuilds the table.
file(GLOB_RECURSE files RELATIVE ${DIR} ${DIR}/*.json)
list(SORT files)
set(body "")
foreach(f ${files})
  file(READ ${DIR}/${f} text)
  string(APPEND body "    {\"${f}\", R\"svxdata(${text})svxdata\"},\n")
endforeach()
file(WRITE ${OUT}.tmp "// generated by cmake/embed_data.cmake: do not edit\n#include \"${HEADER}\"\n\nnamespace ${NAMESPACE} {\n\nconst std::vector<EmbeddedFile>& ${FUNCTION}() {\n  static const std::vector<EmbeddedFile> t = {\n${body}  };\n  return t;\n}\n\n}  // namespace ${NAMESPACE}\n")
file(COPY_FILE ${OUT}.tmp ${OUT} ONLY_IF_DIFFERENT)
