# Writes OUT: the preset files under DIR (data/presets/**/*.json) as a C++ table of
# {path, text} (svx/procgen/presets.hpp: embedded_presets), so that every build - WASM too -
# carries them. Run at build time (add_custom_command): a changed preset rebuilds the table.
file(GLOB_RECURSE files RELATIVE ${DIR} ${DIR}/*.json)
list(SORT files)
set(body "")
foreach(f ${files})
  file(READ ${DIR}/${f} text)
  string(APPEND body "    {\"${f}\", R\"svxpreset(${text})svxpreset\"},\n")
endforeach()
file(WRITE ${OUT}.tmp "// generated by cmake/embed_presets.cmake from data/presets: do not edit\n#include \"svx/procgen/presets.hpp\"\n\nnamespace svx {\n\nconst std::vector<EmbeddedPreset>& embedded_presets() {\n  static const std::vector<EmbeddedPreset> t = {\n${body}  };\n  return t;\n}\n\n}  // namespace svx\n")
file(COPY_FILE ${OUT}.tmp ${OUT} ONLY_IF_DIFFERENT)
